version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todolist-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todolist
  mongo-express:
    image: mongo-express:latest
    container_name: local-mongo-express
    depends_on:
    - mongo
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
    - "8081:8081"

volumes:
  mongodb_data:
    name: todolist-mongodb-data