openapi: 3.0.0
info:
  title: TodoList API
  description: API for managing todo lists and their tasks
  version: 1.0.0

servers:
- url: http://localhost:3000/api
  description: Local development server

paths:
  /todolists:
    get:
      summary: Get all todo lists
      responses:
        '200':
          description: A list of todo lists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
        '500':
          description: Server error
    
    post:
      summary: Create a new todo list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              properties:
                name:
                  type: string
                tasks:
                  type: array
                  items:
                    $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Todo list created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '400':
          description: Invalid request

  /todolists/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    
    get:
      summary: Get a specific todo list
      responses:
        '200':
          description: The todo list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '404':
          description: Todo list not found
    
    put:
      summary: Update a todo list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                tasks:
                  type: array
                  items:
                    $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Todo list updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '404':
          description: Todo list not found
    
    delete:
      summary: Delete a todo list
      responses:
        '200':
          description: Todo list deleted
        '404':
          description: Todo list not found

  /todolists/{id}/tasks:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    
    post:
      summary: Add a task to a todo list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '404':
          description: Todo list not found

  /todolists/{id}/tasks/{taskId}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    - name: taskId
      in: path
      required: true
      schema:
        type: string
    
    put:
      summary: Update a task in a todo list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '404':
          description: Todo list or task not found
    
    delete:
      summary: Delete a task from a todo list
      responses:
        '200':
          description: Task deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '404':
          description: Todo list or task not found

  /todolists/stats:
    get:
      summary: Get tasks stats by priority
      description: Return an array of objects describing how many tasks have each priority
      responses:
        '200':
          description: Stats by priority
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PriorityStats'
        '500':
          description: Server error

components:
  schemas:
    Task:
      type: object
      required:
      - title
      properties:
        title:
          type: string
        description:
          type: string
        done:
          type: boolean
          default: false
        dueDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        priority:
          type: string
          enum: [low, medium, high]
          default: medium

    TodoList:
      type: object
      required:
      - name
      properties:
        _id:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    PriorityStats:
      type: object
      properties:
        _id:
          type: string
          description: Priority level (low, medium, or high)
        count:
          type: integer
          description: Number of tasks with this priority
